services:
  backend:
    build: ../backend
    healthcheck:
      test: ["CMD", "echo", "OK"] # TODO: implement healthcheck in Django
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # adjust as needed
        max-file: "3"

  webapp:
    build: ../webapp
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "echo", "OK"] # TODO: implement healthcheck in frontend
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # adjust as needed
        max-file: "3"
