services:
  backend:
    volumes:
      - ../backend:/app
      - /app/.venv # anonymous volume: to avoid python environment from being erased during the mapping
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  webapp:
    volumes:
      - ../webapp:/app
      - /app/node_modules # anonymous volume: to avoid node modules from being erased during the mapping
    ports:
      - "5173:5173"
    command: ["npm", "run", "docker:dev"]
