services:
  backend:
    volumes:
      - ../backend:/app # map local backend directory to container's /app directory for reactive development
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=john
      - DJANGO_SUPERUSER_EMAIL=john.doe@example.com
      - DJANGO_SUPERUSER_PASSWORD=doe
      - WHITENOISE_AUTOREFRESH=True
    env_file: "../.env"

  webapp:
    volumes:
      - ../webapp:/app
      - /app/node_modules # anonymous volume: to avoid node modules from being erased during the mapping
    ports:
      - "5173:5173"
    command: ["npm", "run", "docker:dev"]
