# Generated by Django 4.2.2 on 2025-05-09 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consumption",
            options={
                "ordering": ("year", "month"),
                "verbose_name": "Consumption",
                "verbose_name_plural": "Consumptions",
            },
        ),
    ]
