# Generated by Django 4.2.2 on 2025-05-09 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_consumption_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ElectricityPrice",
        ),
        migrations.AlterModelOptions(
            name="consumption",
            options={
                "ordering": ("-year", "-month"),
                "verbose_name": "Consumption",
                "verbose_name_plural": "Consumptions",
            },
        ),
    ]
