# Generated by Django 4.2.2 on 2025-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_delete_electricityprice_alter_consumption_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="consumption",
            options={
                "ordering": ("client_id", "-year", "-month"),
                "verbose_name": "Consumption",
                "verbose_name_plural": "Consumptions",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="has_anomaly",
            field=models.BooleanField(default=False, verbose_name="has anomaly"),
        ),
        migrations.AddField(
            model_name="client",
            name="has_elec_heat",
            field=models.BooleanField(
                default=False, verbose_name="has electrical heating"
            ),
        ),
    ]
