# Generated by Django 4.2.2 on 2025-05-10 13:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_client_options_alter_consumption_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="month",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="year")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.client",
                        verbose_name="client",
                    ),
                ),
            ],
            options={
                "ordering": ("client_id", "-year", "-month"),
                "unique_together": {("client", "month", "year")},
            },
        ),
    ]
