# Generated by Django 4.2.2 on 2025-05-10 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_anomaly"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={},
        ),
        migrations.RemoveField(
            model_name="client",
            name="has_anomaly",
        ),
        migrations.RemoveField(
            model_name="client",
            name="has_elec_heat",
        ),
        migrations.DeleteModel(
            name="Anomaly",
        ),
    ]
