# Generated by Django 4.2.2 on 2025-05-11 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_client_options_remove_client_has_anomaly_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("id",)},
        ),
    ]
