# Generated by Django 5.2.12 on 2026-04-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='project',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='projet'),
        ),
    ]
