# Generated by Django 5.2.14 on 2026-07-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('add_data', 'Can add data'), ('view_data', 'Can view data'), ('change_data', 'Can change data'), ('delete_data', 'Can delete data')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
