# Generated by Django 5.2.15 on 2026-07-05 19:06

from django.db import migrations, models
import json


def convert_project_to_json(apps, schema_editor):
    """Convert existing string project values to JSON arrays"""
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        if user.project:
            # Convert non-null strings to a list containing that string
            if isinstance(user.project, str):
                user.project = json.dumps([user.project])
                user.save(update_fields=['project'])


def reverse_convert_project_to_json(apps, schema_editor):
    """Reverse: not typically needed but keeping for safety"""
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        if user.project:
            # Convert non-null lists to a concatenated string containing every element of the list
            if isinstance(user.project, list):
                user.project = ",".join(user.project)
                user.save(update_fields=['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.RunPython(convert_project_to_json, reverse_convert_project_to_json),
        migrations.AlterField(
            model_name='customuser',
            name='project',
            field=models.JSONField(blank=True, null=True, verbose_name='projet'),
        ),
    ]
