# Generated by Django 5.2.15 on 2026-07-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='project',
            field=models.JSONField(blank=True, default=list, verbose_name='projet'),
        ),
    ]
